#!/bin/bash

if [ "$#" == "0" ]; then
  echo "Usage: check <NAME>"
  exit 1
fi

NAME=$1

TLDS=('.com' '.io' '.net')

declare -A SERVICES
SERVICES=(
  [GitHub]="https://github.com/$NAME"
  [Instagram]="https://www.instagram.com/$NAME/"
  [YouTube]="https://www.youtube.com/user/$NAME"
)

print_result() {
  label=$1;
  res=$2;
  exp_res=$3;
  if [ $res -eq $exp_res ]; then
    printf " %25s: \e[1m\e[32mAVAILABLE\e[0m\n" $label;
  else
    printf " %25s: \e[1m\e[31mTAKEN\e[0m\n" $label;
  fi
}

check_tld(){
  domain="$NAME$1"
  whois $domain | grep -Ecq "^NOT FOUND|^No match"
  result=$?
  expected_result=0
  print_result $domain $result $expected_result
}

check_svc(){
  svc_name=$1
  svc_url=${SERVICES[$svc_name]}
  result=$(curl -s -o /dev/null -w '%{http_code}' "$svc_url")
  print_result $svc_name $result 404
}

for tld in "${TLDS[@]}"; do check_tld "$tld" & done; wait; echo
for svc in "${!SERVICES[@]}"; do check_svc "$svc" & done; wait; echo
